# Generated by Django 4.2.7 on 2023-11-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='descriptions',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
